### ISSUE TITLE
Return values of methods

### ISSUE THREAD

**Issue by vogtp** [drewwhis/pybricks-stubs#15]
Is there a reason why methods that would return a value, don't actually do so?
(I am new to python, so I might miss something.)

I am aware that these are only stubs, but the linter gives me errors like "Assigning result of a function call, where the function has no returnpylint(assignment-from-no-return)" which I would like to avoid and my test show that this is easily avoided by returning some dummy value (e.g. 0 or []).

I would be happy to fix it myself and create a pull request, if you want me to.
And thanks for the nice work, makes ev3 programming so much easier and more fun.

**Comment by drewwhis** [comment]
@vogtp When you say "methods that would return a value," which methods are you referring to?

**Comment by vogtp** [comment]
In the example below you see an added `return 0` when the method would return int:

class UltrasonicSensor:

    def distance(self, silent: bool = False) -> int:
         ...
        return 0
