### ISSUE TITLE
New version of pybricks 2.0

### ISSUE THREAD

**Issue by KawaGeo** [drewwhis/pybricks-stubs#18]
Are you planning to upgrade your pybricks-stubs to follow the new version of pybricks 2.0?

**Comment by minetonight** [comment]
I was about to create the same question, so yes, we are a croud :) https://pybricks.com/downloads/

**Comment by drewwhis** [comment]
Yes! I will hopefully get the current package published to an official 1.0.0 version tonight and start upgrading to 2.0 before the weekend.

Assuming the VS Code extension hasn't added that functionality, at least!

**Comment by KawaGeo** [comment]
Great! Am looking forward to having the new version of
pybricks-stubs available.

**Comment by drewwhis** [comment]
For those following, the changes have been written for 2.0.0 and I'm testing them now!

**Comment by drewwhis** [comment]
@KawaGeo @minetonight the package has been updated for version 2.0.0 and is now available to install via pip!
