### ISSUE TITLE
pip command

### ISSUE THREAD

**Issue by KawaGeo** [drewwhis/pybricks-stubs#21]
Unable to install the new version of pybricks-stups (2.0.0). Here is the error message:
B:\>pip install pybricks-stubs
Requirement already satisfied: pybricks-stubs in c:\users\kawag\appdata\local\programs\python\python37-32\lib\site-packages (0.0.6)

**Comment by KawaGeo** [comment]
Found a solution.
Since I already had the old version (0.0.6), the solution is:
  pip install pybricks-stubs==2.0.0

**Comment by drewwhis** [comment]
To upgrade (in general) this should give you the latest:

`pip install [package] -U`

Or

`pip install [package] --upgrade`
