### ISSUE TITLE
[QUESTION] Editing the default settings.json

### ISSUE THREAD

**Issue by KawaGeo** [drewwhis/pybricks-stubs#26]
How do we edit the default settings.json so that we don't have to edit the settings.json every time we create a new project?

**Comment by drewwhis** [comment]
That's something that's managed by the LEGO MINDSTORMS EV3 MicroPython extension. You would have to find where that extension stores the template for the settings.json file and edit the template.

**Comment by drewwhis** [comment]
If you're on Windows, it's in `%USERPROFILE%\.vscode\extensions\lego-education.ev3-micropython-2.0.0\resources\template\.vscode`

**Comment by KawaGeo** [comment]
I followed your suggestion with a small modification, "template.vscode" ->
"template\.vscode" and reboot the Windows OS. Nothing has changed.

**Comment by drewwhis** [comment]
So, to confirm:
1) You edited the `settings.json` file in `%USERPROFILE%\.vscode\extensions\lego-education.ev3-micropython-2.0.0\resources\template\.vscode` to change the setting.
2) You created a new project after making that change.
3) The new project's settings file did not have the setting you put in the template.

Is that correct?

**Comment by drewwhis** [comment]
Ah, looks like that isn't the file that gets used.

You'd need to edit the `settings.json` file in _this_ directory instead: `%USERPROFILE%\.vscode\extensions\lego-education.ev3-micropython-2.0.0\resources\projects\new_project\.vscode`

That's not what I'd expect, but that seems to work.

**Comment by KawaGeo** [comment]
Finally, it works. It is the new project folder to change anything you
want, including main.py file.
